# Generated by Django 2.0.3 on 2018-03-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '微信会员管理', 'verbose_name_plural': '微信会员管理'},
        ),
    ]
