# Generated by Django 2.0.3 on 2018-03-22 09:21

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='appkey',
            field=models.CharField(blank=True, db_index=True, max_length=16, unique=True, verbose_name='认证标示'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.DeviceModel', verbose_name='机器型号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='secret',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='认证秘钥'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='free', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='records',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='success', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
