# Generated by Django 2.0.3 on 2018-03-20 08:27

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_devicemodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '设备列表', 'verbose_name_plural': '设备列表'},
        ),
        migrations.AlterModelOptions(
            name='devicemodel',
            options={'verbose_name': '设备型号', 'verbose_name_plural': '设备型号'},
        ),
        migrations.AddField(
            model_name='device',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='device',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='normal', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='device',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AlterField(
            model_name='device',
            name='appkey',
            field=models.CharField(blank=True, db_index=True, max_length=16, unique=True, verbose_name='APPKEY'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=23, unique=True, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='device',
            name='secret',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SECRET'),
        ),
    ]
