# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-18 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publisher', '0001_initial'),
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.Topic'),
        ),
        migrations.AddField(
            model_name='client',
            name='auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Auth'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.ClientId'),
        ),
        migrations.AddField(
            model_name='client',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.Server'),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set([('host', 'port')]),
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together=set([('client', 'topic')]),
        ),
    ]
