# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-18 12:41
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_auto_20180318_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secureconf',
            name='ca_certs',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/bopo/develop/projects/sensor/server/config/../../private'), upload_to='ca'),
        ),
        migrations.AlterField(
            model_name='secureconf',
            name='certfile',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/bopo/develop/projects/sensor/server/config/../../private'), upload_to='certs'),
        ),
        migrations.AlterField(
            model_name='secureconf',
            name='keyfile',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/bopo/develop/projects/sensor/server/config/../../private'), upload_to='keys'),
        ),
    ]
